FROM openjdk:8u191-jre-alpine3.8
RUN apk add curl jq
ENV PATH $PATH:/usr/lib/jvm/java-1.8-openjdk/bin
WORKDIR /usr/share/manman
ADD target/selenium-docker.jar  		selenium-docker.jar
ADD target/selenium-docker-tests.jar  	selenium-docker-tests.jar
ADD target/libs							libs
ADD testng.xml							testng.xml
ADD healthcheck.sh						healthcheck.sh
ENTRYPOINT java -cp selenium-docker-tests.jar:selenium-docker.jar:libs/* -DHUB_HOST=$HUB_HOST org.testng.TestNG $Module